# Generated by Django 2.0.3 on 2019-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190718_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
