# Generated by Django 2.0.3 on 2019-07-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190718_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='topping_allow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='topping_allow',
            field=models.IntegerField(default=0),
        ),
    ]
